### PR TITLE
At least cmake + Qt 5.15 works fine without QT_EXTRA_LIBS

### LINKED ISSUE #9: removing bluetooth support?
If build this project https://github.com/OlivierLDff/QQuickStaticHelloWorld without any bluetooth dependencies **but**  the resulted binary depend on `CoreBluetooth.framework`:
```
$ grep CoreBluetooth.framework build_ios/Debug-iphoneos/QQuickStaticHelloWorld.app/QQuickStaticHelloWorld
Binary file build_ios/Debug-iphoneos/QQuickStaticHelloWorld.app/QQuickStaticHelloWorld matches
```
The problem is that if upload such application to Apple Store, then Apple ask to explain why you need bluetooth.
I see only one user of `CoreBluetooth.framework` in Qt installation:
```
$ grep CoreBluetooth.framework ~/Qt/5.15.0/ios/lib/*.a
Binary file ~/Qt/5.15.0/ios/lib/libQt5Bluetooth_debug.a matches
```
and clearly QQuickStaticHelloWorld don't depend on `Qt5Bluetooth` but for some reason
it pulls it's dependencies. 

I build project in such way:
```
cmake -DCMAKE_PREFIX_PATH=~/Qt/5.15.0/ios -DDEPLOYMENT_TARGET=12.0 \
-DCMAKE_TOOLCHAIN_FILE=./IosCMakeToolchain/ios.toolchain.cmake -DPLATFORM=OS64 \
-G "Xcode" -DENABLE_BITCODE=FALSE -DENABLE_VISIBILITY=TRUE \
-DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/ ..
xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
```

### PR DESCRIPTION
**Pull request by Dushistov**
I made clean build of my application with this "fix" and it compiles and run on real iOS device just fine. 

fix #9

### CODE REVIEW

**Comment by OlivierLDff** [comment]
I approve the fact we need to move to Qt 5.15. Can you add a note in Readme.md for users using version other than 5.15.

If you are using Qt version lower than 5.15 you might need to add some required link flags by hand if you have undefined symbols. For example:
``` cmake
target_link_libraries(MyApp PUBLIC "-framework Foundation -framework AVFoundation -framework SystemConfiguration -framework AssetsLibrary -framework OpenGLES \
     -framework CoreText -framework QuartzCore -framework CoreGraphics -framework ImageIO -framework Security -framework UIKit -framework WebKit \
    -framework CoreBluetooth -framework MobileCoreServices -framework QuickLook -framework AudioToolbox -framework CoreLocation \
    -framework Accelerate -framework CoreMedia -framework CoreVideo -framework MediaToolbox -framework MediaPlayer -framework GameController
    -framework CoreMotion -framework StoreKit -weak_framework Metal -lz")
```

**Comment by Dushistov** [comment]
> Can you add a note in Readme.md for users using version other than 5.15.

Done. Actually, I leave `QT_EXTRA_LIBS` variable just for this case.
I removed setting of this variable, but it is still in use. May be in future versions of Qt it also can be useful, if there are some kind of bug in cmake/prl.

**Comment by OlivierLDff** [comment]
Perfect thank you!

**Comment by OlivierLDff** [comment]
Github didn't seem to like the indentation before ` ``` `. I edited that.
I also added changed to `target_link_libraries` i think it's more elegant. User shouldn't user internal variable of the function as part of the API.

**Comment by Dushistov** [comment]
@OlivierLDff 

> I also added changed to target_link_libraries i think it's more elegant.

I think the opposite :) The `QT_EXTRA_LIBS` make possible to distinguish between "this is my dependencies" and this is "Qt dependencies'.  But this is not important for me, because of I use 5.15 anyway.

**Comment by OlivierLDff** [comment]
Yes i see what you mean, but i find it to "hacky" to set QT_EXTRA_LIBS before calling the function. Anyway at the end the script is calling `target_link_libraries `, so better make it clear.

**Pull request merged**
